// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: 1111

#ifndef _1111_UI_H
#define _1111_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
void r_Animation(lv_obj_t * TargetObject, int delay);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_air_png);    // assets\air.png
LV_IMG_DECLARE(ui_img_pointer_png);    // assets\pointer.png
LV_IMG_DECLARE(ui_img_light1_png);    // assets\light1.png
LV_IMG_DECLARE(ui_img_light2_png);    // assets\light2.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
